language: android

android:
  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - build-tools-26.0.2
    - android-26
licenses:
    - 'android-sdk-license-.+'
    - '.+'


script:
  - ./gradlew build

before_install:
  - chmod +x gradlew

notifications:
  email:
    on_success: never
    on_failure: always
